// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtzvkfjvxtsdiydmyygh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0enZrZmp2eHRzZGl5ZG15eWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzMxMjYsImV4cCI6MjA3MDc0OTEyNn0.LlOPaIh0bXmL63-GVkwY3tT_msvT_IqyjR7yqoH0M2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});